### ISSUE TITLE
How to setup "OAuth2.0 Tutorial Page" ?

### ISSUE THREAD

**Issue by spinnaker1** [hunterdp/fitbit-tracker#1]
Can you explain how to correctly setup the "OAuth 2.0 tutorial page" on dev.fitbit.com?

I don't know what redirect URL to use and how to get the access token and refresh token and the other values that go into your "config.json".

**Comment by hunterdp** [comment]
1.  Create an account.
2.  Register an application.  
 - It really doesn't matter what the call back URI is.  
 - Make sure it is a "Personal OAuth2.0 Type"
3.  Once done, you will get a page that has the following value:
OAuth 2.0 Client ID: 
Client Secret: 
Callback URL: 
4.  Click on the OAutho 2.0 tutorial lik at the bottom of the page and follow the directions to get the rest of the values.
